name: sky
description: Command-line connector tool for Fexr.
version: 0.1.0
homepage: https://getfexr.com
repository: https://github.com/getfexr/sky

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  husky: ^0.1.4+2
  lint_staged: ^0.1.2
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  args: ^2.3.1
  grpc: ^3.0.2
  hive: ^2.2.3
  protobuf: ^2.1.0
  logger: ^1.1.0
  crypto: ^3.0.2
  dotenv: ^4.0.1
  jaguar_jwt: ^3.0.0
  http: ^0.13.5

lint_staged:
  .dart: dart format --fix && dart fix --apply