name: sky
description: Command-line connector tool for Fexr.
version: 0.1.0
homepage: https://getfexr.com
repository: https://github.com/getfexr/sky

environment:
  sdk: '>=2.19.0-146.2.beta <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  args: ^2.3.1
  cron: ^0.5.0
  grpc: ^3.0.2
  hive: ^2.2.3
